#! /bin/sh

bspc monitor -d 1 2 3 4 5

bspc config border_width        0
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config bottom_padding	24
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
