#! /bin/sh

sxhkd -m -1 &
exec ~/.xinitrc &

bspc monitor -d web chat music term code misc

bspc config border_width          5
bspc config window_gap            24
bspc config split_ratio           0.66
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config bottom_padding        72
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Vivaldi desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell manage=off

bspc config normal_border_color "#282828"
bspc config focused_border_color "#b16286"
bspc config presel_border_color "#458588"
